// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prototest.proto

package org.rocksdbprotobuf.proto;

public final class Prototest {
  private Prototest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Type1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .Type1.Subtype11 subtype11 = 1;
    /**
     * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
     */
    boolean hasSubtype11();
    /**
     * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
     */
    org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 getSubtype11();
    /**
     * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
     */
    org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11OrBuilder getSubtype11OrBuilder();

    // repeated string text12 = 2;
    /**
     * <code>repeated string text12 = 2;</code>
     */
    java.util.List<java.lang.String>
    getText12List();
    /**
     * <code>repeated string text12 = 2;</code>
     */
    int getText12Count();
    /**
     * <code>repeated string text12 = 2;</code>
     */
    java.lang.String getText12(int index);
    /**
     * <code>repeated string text12 = 2;</code>
     */
    com.google.protobuf.ByteString
        getText12Bytes(int index);

    // optional string text13 = 3;
    /**
     * <code>optional string text13 = 3;</code>
     */
    boolean hasText13();
    /**
     * <code>optional string text13 = 3;</code>
     */
    java.lang.String getText13();
    /**
     * <code>optional string text13 = 3;</code>
     */
    com.google.protobuf.ByteString
        getText13Bytes();
  }
  /**
   * Protobuf type {@code Type1}
   */
  public static final class Type1 extends
      com.google.protobuf.GeneratedMessage
      implements Type1OrBuilder {
    // Use Type1.newBuilder() to construct.
    private Type1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Type1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Type1 defaultInstance;
    public static Type1 getDefaultInstance() {
      return defaultInstance;
    }

    public Type1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Type1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = subtype11_.toBuilder();
              }
              subtype11_ = input.readMessage(org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subtype11_);
                subtype11_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                text12_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              text12_.add(input.readBytes());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              text13_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          text12_ = new com.google.protobuf.UnmodifiableLazyStringList(text12_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rocksdbprotobuf.proto.Prototest.Type1.class, org.rocksdbprotobuf.proto.Prototest.Type1.Builder.class);
    }

    public static com.google.protobuf.Parser<Type1> PARSER =
        new com.google.protobuf.AbstractParser<Type1>() {
      public Type1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Type1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Type1> getParserForType() {
      return PARSER;
    }

    public interface Subtype11OrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string text111 = 1;
      /**
       * <code>optional string text111 = 1;</code>
       *
       * <pre>
       * This field has merge type 1
       * </pre>
       */
      boolean hasText111();
      /**
       * <code>optional string text111 = 1;</code>
       *
       * <pre>
       * This field has merge type 1
       * </pre>
       */
      java.lang.String getText111();
      /**
       * <code>optional string text111 = 1;</code>
       *
       * <pre>
       * This field has merge type 1
       * </pre>
       */
      com.google.protobuf.ByteString
          getText111Bytes();

      // repeated string text112 = 2;
      /**
       * <code>repeated string text112 = 2;</code>
       */
      java.util.List<java.lang.String>
      getText112List();
      /**
       * <code>repeated string text112 = 2;</code>
       */
      int getText112Count();
      /**
       * <code>repeated string text112 = 2;</code>
       */
      java.lang.String getText112(int index);
      /**
       * <code>repeated string text112 = 2;</code>
       */
      com.google.protobuf.ByteString
          getText112Bytes(int index);
    }
    /**
     * Protobuf type {@code Type1.Subtype11}
     */
    public static final class Subtype11 extends
        com.google.protobuf.GeneratedMessage
        implements Subtype11OrBuilder {
      // Use Subtype11.newBuilder() to construct.
      private Subtype11(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Subtype11(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Subtype11 defaultInstance;
      public static Subtype11 getDefaultInstance() {
        return defaultInstance;
      }

      public Subtype11 getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Subtype11(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                text111_ = input.readBytes();
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  text112_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                text112_.add(input.readBytes());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            text112_ = new com.google.protobuf.UnmodifiableLazyStringList(text112_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_Subtype11_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_Subtype11_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.class, org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.Builder.class);
      }

      public static com.google.protobuf.Parser<Subtype11> PARSER =
          new com.google.protobuf.AbstractParser<Subtype11>() {
        public Subtype11 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Subtype11(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Subtype11> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string text111 = 1;
      public static final int TEXT111_FIELD_NUMBER = 1;
      private java.lang.Object text111_;
      /**
       * <code>optional string text111 = 1;</code>
       *
       * <pre>
       * This field has merge type 1
       * </pre>
       */
      public boolean hasText111() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string text111 = 1;</code>
       *
       * <pre>
       * This field has merge type 1
       * </pre>
       */
      public java.lang.String getText111() {
        java.lang.Object ref = text111_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text111_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string text111 = 1;</code>
       *
       * <pre>
       * This field has merge type 1
       * </pre>
       */
      public com.google.protobuf.ByteString
          getText111Bytes() {
        java.lang.Object ref = text111_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text111_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // repeated string text112 = 2;
      public static final int TEXT112_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList text112_;
      /**
       * <code>repeated string text112 = 2;</code>
       */
      public java.util.List<java.lang.String>
          getText112List() {
        return text112_;
      }
      /**
       * <code>repeated string text112 = 2;</code>
       */
      public int getText112Count() {
        return text112_.size();
      }
      /**
       * <code>repeated string text112 = 2;</code>
       */
      public java.lang.String getText112(int index) {
        return text112_.get(index);
      }
      /**
       * <code>repeated string text112 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getText112Bytes(int index) {
        return text112_.getByteString(index);
      }

      private void initFields() {
        text111_ = "";
        text112_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getText111Bytes());
        }
        for (int i = 0; i < text112_.size(); i++) {
          output.writeBytes(2, text112_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getText111Bytes());
        }
        {
          int dataSize = 0;
          for (int i = 0; i < text112_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(text112_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getText112List().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Type1.Subtype11}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_Subtype11_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_Subtype11_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.class, org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.Builder.class);
        }

        // Construct using org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          text111_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          text112_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_Subtype11_descriptor;
        }

        public org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 getDefaultInstanceForType() {
          return org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.getDefaultInstance();
        }

        public org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 build() {
          org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 buildPartial() {
          org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 result = new org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.text111_ = text111_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            text112_ = new com.google.protobuf.UnmodifiableLazyStringList(
                text112_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.text112_ = text112_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11) {
            return mergeFrom((org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 other) {
          if (other == org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.getDefaultInstance()) return this;
          if (other.hasText111()) {
            bitField0_ |= 0x00000001;
            text111_ = other.text111_;
            onChanged();
          }
          if (!other.text112_.isEmpty()) {
            if (text112_.isEmpty()) {
              text112_ = other.text112_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureText112IsMutable();
              text112_.addAll(other.text112_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string text111 = 1;
        private java.lang.Object text111_ = "";
        /**
         * <code>optional string text111 = 1;</code>
         *
         * <pre>
         * This field has merge type 1
         * </pre>
         */
        public boolean hasText111() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string text111 = 1;</code>
         *
         * <pre>
         * This field has merge type 1
         * </pre>
         */
        public java.lang.String getText111() {
          java.lang.Object ref = text111_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            text111_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string text111 = 1;</code>
         *
         * <pre>
         * This field has merge type 1
         * </pre>
         */
        public com.google.protobuf.ByteString
            getText111Bytes() {
          java.lang.Object ref = text111_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            text111_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string text111 = 1;</code>
         *
         * <pre>
         * This field has merge type 1
         * </pre>
         */
        public Builder setText111(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          text111_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string text111 = 1;</code>
         *
         * <pre>
         * This field has merge type 1
         * </pre>
         */
        public Builder clearText111() {
          bitField0_ = (bitField0_ & ~0x00000001);
          text111_ = getDefaultInstance().getText111();
          onChanged();
          return this;
        }
        /**
         * <code>optional string text111 = 1;</code>
         *
         * <pre>
         * This field has merge type 1
         * </pre>
         */
        public Builder setText111Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          text111_ = value;
          onChanged();
          return this;
        }

        // repeated string text112 = 2;
        private com.google.protobuf.LazyStringList text112_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureText112IsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            text112_ = new com.google.protobuf.LazyStringArrayList(text112_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public java.util.List<java.lang.String>
            getText112List() {
          return java.util.Collections.unmodifiableList(text112_);
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public int getText112Count() {
          return text112_.size();
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public java.lang.String getText112(int index) {
          return text112_.get(index);
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public com.google.protobuf.ByteString
            getText112Bytes(int index) {
          return text112_.getByteString(index);
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public Builder setText112(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureText112IsMutable();
          text112_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public Builder addText112(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureText112IsMutable();
          text112_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public Builder addAllText112(
            java.lang.Iterable<java.lang.String> values) {
          ensureText112IsMutable();
          super.addAll(values, text112_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public Builder clearText112() {
          text112_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string text112 = 2;</code>
         */
        public Builder addText112Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureText112IsMutable();
          text112_.add(value);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Type1.Subtype11)
      }

      static {
        defaultInstance = new Subtype11(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Type1.Subtype11)
    }

    private int bitField0_;
    // optional .Type1.Subtype11 subtype11 = 1;
    public static final int SUBTYPE11_FIELD_NUMBER = 1;
    private org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 subtype11_;
    /**
     * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
     */
    public boolean hasSubtype11() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
     */
    public org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 getSubtype11() {
      return subtype11_;
    }
    /**
     * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
     */
    public org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11OrBuilder getSubtype11OrBuilder() {
      return subtype11_;
    }

    // repeated string text12 = 2;
    public static final int TEXT12_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList text12_;
    /**
     * <code>repeated string text12 = 2;</code>
     */
    public java.util.List<java.lang.String>
        getText12List() {
      return text12_;
    }
    /**
     * <code>repeated string text12 = 2;</code>
     */
    public int getText12Count() {
      return text12_.size();
    }
    /**
     * <code>repeated string text12 = 2;</code>
     */
    public java.lang.String getText12(int index) {
      return text12_.get(index);
    }
    /**
     * <code>repeated string text12 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getText12Bytes(int index) {
      return text12_.getByteString(index);
    }

    // optional string text13 = 3;
    public static final int TEXT13_FIELD_NUMBER = 3;
    private java.lang.Object text13_;
    /**
     * <code>optional string text13 = 3;</code>
     */
    public boolean hasText13() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string text13 = 3;</code>
     */
    public java.lang.String getText13() {
      java.lang.Object ref = text13_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text13_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text13 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getText13Bytes() {
      java.lang.Object ref = text13_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text13_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      subtype11_ = org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.getDefaultInstance();
      text12_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      text13_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, subtype11_);
      }
      for (int i = 0; i < text12_.size(); i++) {
        output.writeBytes(2, text12_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getText13Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, subtype11_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < text12_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(text12_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getText12List().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getText13Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rocksdbprotobuf.proto.Prototest.Type1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Type1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rocksdbprotobuf.proto.Prototest.Type1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rocksdbprotobuf.proto.Prototest.Type1.class, org.rocksdbprotobuf.proto.Prototest.Type1.Builder.class);
      }

      // Construct using org.rocksdbprotobuf.proto.Prototest.Type1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSubtype11FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (subtype11Builder_ == null) {
          subtype11_ = org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.getDefaultInstance();
        } else {
          subtype11Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        text12_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        text13_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rocksdbprotobuf.proto.Prototest.internal_static_Type1_descriptor;
      }

      public org.rocksdbprotobuf.proto.Prototest.Type1 getDefaultInstanceForType() {
        return org.rocksdbprotobuf.proto.Prototest.Type1.getDefaultInstance();
      }

      public org.rocksdbprotobuf.proto.Prototest.Type1 build() {
        org.rocksdbprotobuf.proto.Prototest.Type1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rocksdbprotobuf.proto.Prototest.Type1 buildPartial() {
        org.rocksdbprotobuf.proto.Prototest.Type1 result = new org.rocksdbprotobuf.proto.Prototest.Type1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (subtype11Builder_ == null) {
          result.subtype11_ = subtype11_;
        } else {
          result.subtype11_ = subtype11Builder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          text12_ = new com.google.protobuf.UnmodifiableLazyStringList(
              text12_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.text12_ = text12_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text13_ = text13_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rocksdbprotobuf.proto.Prototest.Type1) {
          return mergeFrom((org.rocksdbprotobuf.proto.Prototest.Type1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rocksdbprotobuf.proto.Prototest.Type1 other) {
        if (other == org.rocksdbprotobuf.proto.Prototest.Type1.getDefaultInstance()) return this;
        if (other.hasSubtype11()) {
          mergeSubtype11(other.getSubtype11());
        }
        if (!other.text12_.isEmpty()) {
          if (text12_.isEmpty()) {
            text12_ = other.text12_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureText12IsMutable();
            text12_.addAll(other.text12_);
          }
          onChanged();
        }
        if (other.hasText13()) {
          bitField0_ |= 0x00000004;
          text13_ = other.text13_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rocksdbprotobuf.proto.Prototest.Type1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rocksdbprotobuf.proto.Prototest.Type1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .Type1.Subtype11 subtype11 = 1;
      private org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 subtype11_ = org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11, org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.Builder, org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11OrBuilder> subtype11Builder_;
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      public boolean hasSubtype11() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      public org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 getSubtype11() {
        if (subtype11Builder_ == null) {
          return subtype11_;
        } else {
          return subtype11Builder_.getMessage();
        }
      }
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      public Builder setSubtype11(org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 value) {
        if (subtype11Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subtype11_ = value;
          onChanged();
        } else {
          subtype11Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      public Builder setSubtype11(
          org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.Builder builderForValue) {
        if (subtype11Builder_ == null) {
          subtype11_ = builderForValue.build();
          onChanged();
        } else {
          subtype11Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      public Builder mergeSubtype11(org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11 value) {
        if (subtype11Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              subtype11_ != org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.getDefaultInstance()) {
            subtype11_ =
              org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.newBuilder(subtype11_).mergeFrom(value).buildPartial();
          } else {
            subtype11_ = value;
          }
          onChanged();
        } else {
          subtype11Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      public Builder clearSubtype11() {
        if (subtype11Builder_ == null) {
          subtype11_ = org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.getDefaultInstance();
          onChanged();
        } else {
          subtype11Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      public org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.Builder getSubtype11Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSubtype11FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      public org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11OrBuilder getSubtype11OrBuilder() {
        if (subtype11Builder_ != null) {
          return subtype11Builder_.getMessageOrBuilder();
        } else {
          return subtype11_;
        }
      }
      /**
       * <code>optional .Type1.Subtype11 subtype11 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11, org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.Builder, org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11OrBuilder> 
          getSubtype11FieldBuilder() {
        if (subtype11Builder_ == null) {
          subtype11Builder_ = new com.google.protobuf.SingleFieldBuilder<
              org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11, org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11.Builder, org.rocksdbprotobuf.proto.Prototest.Type1.Subtype11OrBuilder>(
                  subtype11_,
                  getParentForChildren(),
                  isClean());
          subtype11_ = null;
        }
        return subtype11Builder_;
      }

      // repeated string text12 = 2;
      private com.google.protobuf.LazyStringList text12_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureText12IsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          text12_ = new com.google.protobuf.LazyStringArrayList(text12_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public java.util.List<java.lang.String>
          getText12List() {
        return java.util.Collections.unmodifiableList(text12_);
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public int getText12Count() {
        return text12_.size();
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public java.lang.String getText12(int index) {
        return text12_.get(index);
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getText12Bytes(int index) {
        return text12_.getByteString(index);
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public Builder setText12(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureText12IsMutable();
        text12_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public Builder addText12(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureText12IsMutable();
        text12_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public Builder addAllText12(
          java.lang.Iterable<java.lang.String> values) {
        ensureText12IsMutable();
        super.addAll(values, text12_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public Builder clearText12() {
        text12_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text12 = 2;</code>
       */
      public Builder addText12Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureText12IsMutable();
        text12_.add(value);
        onChanged();
        return this;
      }

      // optional string text13 = 3;
      private java.lang.Object text13_ = "";
      /**
       * <code>optional string text13 = 3;</code>
       */
      public boolean hasText13() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string text13 = 3;</code>
       */
      public java.lang.String getText13() {
        java.lang.Object ref = text13_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text13_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text13 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getText13Bytes() {
        java.lang.Object ref = text13_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text13_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text13 = 3;</code>
       */
      public Builder setText13(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text13_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text13 = 3;</code>
       */
      public Builder clearText13() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text13_ = getDefaultInstance().getText13();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text13 = 3;</code>
       */
      public Builder setText13Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text13_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Type1)
    }

    static {
      defaultInstance = new Type1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Type1)
  }

  public interface Type2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string text21 = 1;
    /**
     * <code>repeated string text21 = 1;</code>
     */
    java.util.List<java.lang.String>
    getText21List();
    /**
     * <code>repeated string text21 = 1;</code>
     */
    int getText21Count();
    /**
     * <code>repeated string text21 = 1;</code>
     */
    java.lang.String getText21(int index);
    /**
     * <code>repeated string text21 = 1;</code>
     */
    com.google.protobuf.ByteString
        getText21Bytes(int index);
  }
  /**
   * Protobuf type {@code Type2}
   *
   * <pre>
   * This message will be ignored
   * </pre>
   */
  public static final class Type2 extends
      com.google.protobuf.GeneratedMessage
      implements Type2OrBuilder {
    // Use Type2.newBuilder() to construct.
    private Type2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Type2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Type2 defaultInstance;
    public static Type2 getDefaultInstance() {
      return defaultInstance;
    }

    public Type2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Type2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                text21_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              text21_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          text21_ = new com.google.protobuf.UnmodifiableLazyStringList(text21_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rocksdbprotobuf.proto.Prototest.internal_static_Type2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rocksdbprotobuf.proto.Prototest.internal_static_Type2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rocksdbprotobuf.proto.Prototest.Type2.class, org.rocksdbprotobuf.proto.Prototest.Type2.Builder.class);
    }

    public static com.google.protobuf.Parser<Type2> PARSER =
        new com.google.protobuf.AbstractParser<Type2>() {
      public Type2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Type2(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Type2> getParserForType() {
      return PARSER;
    }

    // repeated string text21 = 1;
    public static final int TEXT21_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList text21_;
    /**
     * <code>repeated string text21 = 1;</code>
     */
    public java.util.List<java.lang.String>
        getText21List() {
      return text21_;
    }
    /**
     * <code>repeated string text21 = 1;</code>
     */
    public int getText21Count() {
      return text21_.size();
    }
    /**
     * <code>repeated string text21 = 1;</code>
     */
    public java.lang.String getText21(int index) {
      return text21_.get(index);
    }
    /**
     * <code>repeated string text21 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getText21Bytes(int index) {
      return text21_.getByteString(index);
    }

    private void initFields() {
      text21_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < text21_.size(); i++) {
        output.writeBytes(1, text21_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < text21_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(text21_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getText21List().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rocksdbprotobuf.proto.Prototest.Type2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rocksdbprotobuf.proto.Prototest.Type2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Type2}
     *
     * <pre>
     * This message will be ignored
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rocksdbprotobuf.proto.Prototest.Type2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rocksdbprotobuf.proto.Prototest.internal_static_Type2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rocksdbprotobuf.proto.Prototest.internal_static_Type2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rocksdbprotobuf.proto.Prototest.Type2.class, org.rocksdbprotobuf.proto.Prototest.Type2.Builder.class);
      }

      // Construct using org.rocksdbprotobuf.proto.Prototest.Type2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text21_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rocksdbprotobuf.proto.Prototest.internal_static_Type2_descriptor;
      }

      public org.rocksdbprotobuf.proto.Prototest.Type2 getDefaultInstanceForType() {
        return org.rocksdbprotobuf.proto.Prototest.Type2.getDefaultInstance();
      }

      public org.rocksdbprotobuf.proto.Prototest.Type2 build() {
        org.rocksdbprotobuf.proto.Prototest.Type2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rocksdbprotobuf.proto.Prototest.Type2 buildPartial() {
        org.rocksdbprotobuf.proto.Prototest.Type2 result = new org.rocksdbprotobuf.proto.Prototest.Type2(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          text21_ = new com.google.protobuf.UnmodifiableLazyStringList(
              text21_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.text21_ = text21_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rocksdbprotobuf.proto.Prototest.Type2) {
          return mergeFrom((org.rocksdbprotobuf.proto.Prototest.Type2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rocksdbprotobuf.proto.Prototest.Type2 other) {
        if (other == org.rocksdbprotobuf.proto.Prototest.Type2.getDefaultInstance()) return this;
        if (!other.text21_.isEmpty()) {
          if (text21_.isEmpty()) {
            text21_ = other.text21_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureText21IsMutable();
            text21_.addAll(other.text21_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rocksdbprotobuf.proto.Prototest.Type2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rocksdbprotobuf.proto.Prototest.Type2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string text21 = 1;
      private com.google.protobuf.LazyStringList text21_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureText21IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          text21_ = new com.google.protobuf.LazyStringArrayList(text21_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public java.util.List<java.lang.String>
          getText21List() {
        return java.util.Collections.unmodifiableList(text21_);
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public int getText21Count() {
        return text21_.size();
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public java.lang.String getText21(int index) {
        return text21_.get(index);
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getText21Bytes(int index) {
        return text21_.getByteString(index);
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public Builder setText21(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureText21IsMutable();
        text21_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public Builder addText21(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureText21IsMutable();
        text21_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public Builder addAllText21(
          java.lang.Iterable<java.lang.String> values) {
        ensureText21IsMutable();
        super.addAll(values, text21_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public Builder clearText21() {
        text21_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text21 = 1;</code>
       */
      public Builder addText21Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureText21IsMutable();
        text21_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Type2)
    }

    static {
      defaultInstance = new Type2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Type2)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Type1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Type1_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Type1_Subtype11_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Type1_Subtype11_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Type2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Type2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017prototest.proto\032\013merge.proto\032 google/p" +
      "rotobuf/descriptor.proto\"\217\001\n\005Type1\022#\n\tsu" +
      "btype11\030\001 \001(\0132\020.Type1.Subtype11\022\030\n\006text1" +
      "2\030\002 \003(\tB\010\210\265\030\001\220\265\030\002\022\016\n\006text13\030\003 \001(\t\0327\n\tSub" +
      "type11\022\017\n\007text111\030\001 \001(\t\022\031\n\007text112\030\002 \003(\t" +
      "B\010\210\265\030\001\220\265\030\002\"\027\n\005Type2\022\016\n\006text21\030\001 \003(\tB\033\n\031o" +
      "rg.rocksdbprotobuf.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Type1_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Type1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Type1_descriptor,
              new java.lang.String[] { "Subtype11", "Text12", "Text13", });
          internal_static_Type1_Subtype11_descriptor =
            internal_static_Type1_descriptor.getNestedTypes().get(0);
          internal_static_Type1_Subtype11_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Type1_Subtype11_descriptor,
              new java.lang.String[] { "Text111", "Text112", });
          internal_static_Type2_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Type2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Type2_descriptor,
              new java.lang.String[] { "Text21", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(org.rocksdbprotobuf.proto.Merge.mergeType);
          registry.add(org.rocksdbprotobuf.proto.Merge.mergeCap);
          registry.add(org.rocksdbprotobuf.proto.Merge.mergeType);
          registry.add(org.rocksdbprotobuf.proto.Merge.mergeCap);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.rocksdbprotobuf.proto.Merge.getDescriptor(),
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
