/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdbprotobuf_ProtobufMergeOperator */

#ifndef _Included_org_rocksdbprotobuf_ProtobufMergeOperator
#define _Included_org_rocksdbprotobuf_ProtobufMergeOperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdbprotobuf_ProtobufMergeOperator
 * Method:    newMergeOperatorHandleImpl
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdbprotobuf_ProtobufMergeOperator_newMergeOperatorHandleImpl
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
